openapi: 3.0.0
info:
  title: Social Posts Manager API
  description: API for managing posts, user authentication, and interactions.
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: Local server

tags:
  - name: Authentication
    description: Endpoints related to user authentication
  - name: Posts
    description: Endpoints for managing posts and user interactions
  - name: Health Check
    description: Endpoint for checking the API health status

paths:
  /api/v1/health:
    get:
      tags:
        - Health Check
      summary: Check API health status
      operationId: getStatus
      responses:
        "200":
          description: API is running and healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"

  /api/v1/auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUser"
      responses:
        "201":
          description: User registered successfully

  /api/v1/auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        "200":
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6..."

  /api/v1/posts:
    get:
      tags:
        - Posts
      summary: Get paginated posts
      operationId: getPostsPaginated
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Successfully retrieved paginated posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Post"
                  totalPosts:
                    type: integer
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer


#     post:
#       tags:
#         - Posts
#       summary: Create a new post
#       operationId: createPost
#       requestBody:
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: "#/components/schemas/Post"
#       responses:
#         "201":
#           description: Post created successfully

#   /api/v1/posts/{id}/like:
#     put:
#       tags:
#         - Posts
#       summary: Like or Unlike a post
#       operationId: likePost
#       parameters:
#         - name: id
#           in: path
#           required: true
#           schema:
#             type: string
#       responses:
#         "200":
#           description: Post liked/unliked

components:
  schemas:
    RegisterUser:
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
        - username
      properties:
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        password:
          type: string
          format: password
          example: "strongpassword123"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        username:
          type: string
          example: "johndoe"

    LoginUser:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "johndoe"
        password:
          type: string
          format: password
          example: "strongpassword123"

    Post:
      type: object
      required:
        - title
        - body
      properties:
        title:
          type: string
          example: "My First Post"
        body:
          type: string
          example: "This is the content of my first post."
        createdAt:
          type: string
          format: date-time
          example: "2025-03-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-03-02T15:30:00Z"
